-- PRODUCT INSIGHTS
-- What are the top 5 best selling products
select p.product_name as Best_product_sell
from products p join order_items o
on p.product_id = o.product_id
group by p.product_name
having count(*)
order by count(*) desc
limit 5;

-- What is the revenue generated by each product
select p.product_name,sum(oi.unit_price) as revenue
from products p left join order_items oi
on p.product_id = oi.product_id
group by p.product_name
order by revenue desc;

-- What is the revenue generated by each products category
select c.category_name,sum(oi.unit_price) as revenue
from categories c join products p 
on c.category_id = p.category_id left join order_items oi
on p.product_id = oi.product_id
group by c.category_name
order by revenue desc;

-- What is the revenue generated by each products category based on completed payments
select c.category_name,sum(pp.amount) as revenue
from categories c join products p 
on c.category_id = p.category_id left join order_items oi
on p.product_id = oi.product_id left join payments pp
on oi.order_id = pp.order_id
where pp.status = 'completed'
group by c.category_name
order by revenue desc; 

-- What is the average product price within each category
select c.category_name,avg(p.price) as avg_product_price
from categories c left join products p
on c.category_id = p.category_id
group by c.category_name;

-- What is the top selling products in each category
select c.category_name,p.product_name,sum(oi.quantity) as selling_products
from categories c join products p
on c.category_id = p.category_id join order_items oi
on p.product_id = oi.product_id
group by c.category_name,p.product_name
order by selling_products desc;

-- What is the top selling products in each category by using window functions
SELECT category_name, product_name, total_sold
FROM (
    SELECT 
        c.category_name,
        p.product_name,
        SUM(oi.quantity) AS total_sold,
        RANK() OVER (
            PARTITION BY c.category_id 
            ORDER BY SUM(oi.quantity) DESC
        ) AS rnk
    FROM categories c
    JOIN products p ON c.category_id = p.category_id
    JOIN order_items oi ON p.product_id = oi.product_id
    GROUP BY c.category_name, p.product_name, c.category_id
) AS ranked_products
WHERE rnk = 1
ORDER BY total_sold desc;

-- What is the average quantity per row within an order
select order_id,avg(quantity) as avg_no_order
from order_items
group by order_id
order by avg_no_order desc;

-- What is the average number of items per order
SELECT 
    AVG(items_per_order) AS avg_items_per_order
FROM (
    SELECT order_id, SUM(quantity) AS items_per_order
    FROM order_items
    GROUP BY order_id
) AS order_summary;


